Controllers/GameController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Wordle.Models;

namespace Wordle.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        private readonly ILogger<GameController> _logger;

        public GameController(ILogger<GameController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            Word word = new Word();
            return View("index", word);
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Wordle.Models;

namespace Wordle.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ScoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Wordle.Models;
using Microsoft.AspNetCore.Identity;
using System.Text.Json;
using Wordle.Areas.Identity.Data;
using System.Text;

namespace Wordle.Controllers
{

    public class ScoreController : Controller
    {
        private readonly AuthDbContext _context;
        private UserManager<User> _userManager;

        public ScoreController(AuthDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        
        public IActionResult Index()
        {
            List<Score> scores = _context.Scores.Where(s => s.User.Id == _userManager.GetUserId(User)).OrderBy(s => s.Date).ToList();
            if(scores == null)
            {
                return NotFound();
            }
            return View("index", scores);
        }

        public IActionResult HighScores()
        {
            List<Score> scores = _context.Scores.Where(s => s.User.Id == _userManager.GetUserId(User)).OrderByDescending(s => s.ScorePoints).Take(3).ToList();
            if (scores == null)
            {
                return NotFound();
            }
            return View("index", scores);
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] Score score)
        {

            System.Security.Claims.ClaimsPrincipal currentUser = this.User;
            var user = await _userManager.GetUserAsync(User); // Get user id:g

            score.User = user;
            score.Date = DateTime.Now;

            _context.Scores.Add(score);
            _context.SaveChanges();

            return new StatusCodeResult(200);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center text-white">
    <div class="container py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5 fw-bold text-uppercase display-6">
        <a class="text-decoration-none text-white" asp-area="" asp-controller="Game" asp-action="Index">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">
                  jouer
              </div>
            </div>
        </a>
        <a class="text-decoration-none text-white" asp-area="" asp-controller="Score" asp-action="Index">
            <div class="card bg-dark text-white mt-5" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">
                  scores
              </div>
            </div>
        </a>
        <a class="text-decoration-none text-white" asp-area="" asp-controller="Score" asp-action="HighScores">
            <div class="card bg-dark text-white mt-5" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">
                  highscores
              </div>
            </div>
        </a>
      </div>
    </div> 
    </div>
</div>